# Build and test stage
FROM maven:3.8.4-openjdk-8-slim AS build
WORKDIR /usr/src/app
COPY . .
RUN mvn clean test package

# Final packaging stage
FROM maven:3.8.4-openjdk-8-slim
WORKDIR /usr/app
COPY --from=build /usr/src/app/target/accenture-techhub-0.0.1-SNAPSHOT.war .
EXPOSE 8080
CMD ["java", "-jar", "accenture-techhub-0.0.1-SNAPSHOT.war"]
